SITE/SITE/SITE/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
 path('siteY/', include('siteY.urls')),
 path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

SITE/SITE/siteY/urls.py
from django.urls import include, path
from . import views

app_name = 'siteY'
urlpatterns = [
    path("login/", views.loginview, name="login"),
    path("criarconta/", views.criarconta, name="criarconta"),
    path("homepage/", views.homepage, name="homepage"),
    path("perfil/", views.perfil, name="perfil"),
    path("addfilme/", views.adicionarfilme, name="addfilme"),
    path("addserie/", views.adicionarserie, name="addserie"),
    path("terminarsessao/", views.terminarsessao, name="terminarsessao"),
    path("listar_filmes/", views.listar_filmes, name="listar_filmes"),
    path("listar_series/", views.listar_series, name="listar_series"),
    path('detalhes_filme/<int:filme_id>/', views.detalhes_filme, name='detalhes_filme'),
    path('detalhes_serie/<int:serie_id>/', views.detalhes_serie, name='detalhes_serie'),
    path('<int:serie_id>/like_serie', views.likepost_serie, name="likepost_serie"),
    path('<int:filme_id>/like_filme', views.likepost_filme, name="likepost_filme"),
    path('serie/<int:serie_id>/adicionar_comentario_serie/', views.adicionar_comentario_serie, name="adicionar_comentario_serie"),
    path('filme/<int:filme_id>/adicionar_comentario_filme/', views.adicionar_comentario_filme, name="adicionar_comentario_filme"),
    path("pesquisar/", views.pesquisar, name="pesquisar"),
    path("meus_dados/", views.meus_dados, name="meus_dados"),
    path("meus_gostos/", views.meus_gostos, name="meus_gostos"),
    path("recuperarPassword", views.recuperarPassword, name='recuperarPassword'),
    path("mudarPass", views.mudarPass, name='mudarPass'),
    path("admin/", views.admin, name="admin"),
    path('apagaruser/<int:user_id>/', views.apagaruser, name='apagaruser'),
    path('editar_user/<int:user_id>/', views.editar_user, name='editar_user'),
    path('<int:filme_id>/editar_filme/', views.editar_filme, name='editar_filme'),
    path('<int:serie_id>/editar_serie/', views.editar_serie, name='editar_serie'),
    path('apagar_filme/<int:filme_id>/', views.apagar_filme, name='apagar_filme'),
    path('apagar_serie/<int:serie_id>/', views.apagar_serie, name='apagar_serie'),
]

SITE/SITE/siteY/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Perfil(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)
    email = models.CharField(max_length=150)
    data_nascimento = models.DateField(null=True)
    nacionalidade = models.CharField(max_length=100)
    genero = models.CharField(max_length=100, blank=True, null=True)
    contacto = models.CharField(max_length=9, blank=True, null=True)
    localidade = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return f'{self.user.username} Profile'


class Filme(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='filmes')
    titulo = models.CharField(max_length=100)
    descricao = models.TextField(blank=True, null=True)
    ano_lancamento = models.PositiveIntegerField(blank=True, null=True)
    duracao_minutos = models.PositiveIntegerField(blank=True, null=True)
    genero = models.CharField(max_length=50, blank=True, null=True)
    imagem = models.ImageField(upload_to='filmes/', blank=True, null=True)
    liked = models.ManyToManyField(User, related_name='filmes_liked', blank=True)
    data_adicao = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.titulo

    @property
    def total_likes_filme(self):
        return self.liked.count()


class Serie(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='series')
    titulo = models.CharField(max_length=100)
    descricao = models.TextField(blank=True, null=True)
    ano_lancamento = models.PositiveIntegerField(blank=True, null=True)
    temporadas = models.PositiveIntegerField(blank=True, null=True)
    episodios = models.PositiveIntegerField(blank=True, null=True)
    genero = models.CharField(max_length=50, blank=True, null=True)
    imagem = models.ImageField(upload_to='series/', blank=True, null=True)
    liked = models.ManyToManyField(User, related_name='series_liked', blank=True)
    data_adicao = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.titulo

    @property
    def total_likes_serie(self):
        return self.liked.count()


LIKE_CHOICES = (
    ('Like', 'Like'), ('Unlike', 'Unlike'),
)


class Like_serie(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    serie = models.ForeignKey(Serie, on_delete=models.CASCADE, null=True, blank=True)
    valor = models.CharField(choices=LIKE_CHOICES, default='like_serie', max_length=10)

    def __str__(self):
        return f"{self.user.username} liked {self.serie}"


class Like_filme(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    filme = models.ForeignKey(Filme, on_delete=models.CASCADE, null=True, blank=True)
    valor = models.CharField(choices=LIKE_CHOICES, default='like_serie', max_length=10)

    def __str__(self):
        return f"{self.user.username} liked {self.filme}"


User
class Comentarios_filme(models.Model):
    filme = models.ForeignKey(Filme, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    date_time = models.DateTimeField(default=timezone.now)
    comentario = models.TextField()

    def __str__(self):
        return self.comentario

class Comentarios_serie(models.Model):
    serie = models.ForeignKey(Serie, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    date_time = models.DateTimeField(default=timezone.now)
    comentario = models.TextField()

    def __str__(self):
        return self.comentario

SITE/SITE/siteY/views.py
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.mail import send_mail
from django.db import IntegrityError
from django.http import HttpResponseRedirect, HttpResponseNotFound, HttpResponseForbidden, HttpResponseNotAllowed
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.html import strip_tags

from .models import Perfil, Filme, Serie, Like_filme, Like_serie, Comentarios_filme, Comentarios_serie


# Create your views here.
def loginview(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('siteY:homepage'))
        else:
            context = {
                'error_message': "Email ou senha incorretos!",
            }
            return render(request, 'siteY/oi.html', context)
    else:
        return render(request, 'siteY/oi.html')



def criarconta(request):
    if request.method == 'POST':
        Username = request.POST['Username']
        Email = request.POST['Email']
        Password = request.POST['Password']
        PrimeiroNome = request.POST['PrimeiroNome']
        UltimoNome = request.POST['UltimoNome']
        Nacionalidade = request.POST['Nacionalidade']
        Genero = request.POST['Genero']
        DataNascimento = request.POST['DataNascimento']


        try:
            user = User.objects.create_user(username=Username, email=Email, password=Password, first_name=PrimeiroNome,
                                            last_name=UltimoNome)
            p = Perfil(user=user, nacionalidade=Nacionalidade, genero=Genero, data_nascimento=DataNascimento)
            p.save()
            return HttpResponseRedirect(reverse('siteY:login'))
        except IntegrityError:
            messages.error(request, 'O Email escolhido já está a ser utilizado. Por favor escolha outro Email')
            return render(request, 'siteY/criarconta.html')

    else:
        return render(request, 'siteY/criarconta.html')



def homepage(request):
    last_added_movies = Filme.objects.order_by('-data_adicao')[:6]
    last_added_series = Serie.objects.order_by('-data_adicao')[:6]
    return render(request, 'siteY/homepage.html', {'last_added_movies': last_added_movies, 'last_added_series': last_added_series})

@login_required(login_url='/siteY/login')
def perfil(request):
    user = request.user
    filmes = Filme.objects.filter(user=user)
    series = Serie.objects.filter(user=user)
    return render(request, 'siteY/perfil.html', {'user': user, 'filmes': filmes, 'series': series})


@login_required(login_url='/siteY/login')
def meus_dados(request):
    user = request.user
    pessoa = user.perfil  # Supondo que o perfil esteja associado ao usuário dessa maneira

    if request.method == 'POST':
        user.email = request.POST.get('Email')
        user.first_name = request.POST.get('PrimeiroNome')
        user.last_name = request.POST.get('UltimoNome')

        password = request.POST.get('Password')
        if password:
            user.set_password(password)
        user.save()

        pessoa.nacionalidade = request.POST.get('Nacionalidade')
        pessoa.contacto = request.POST.get('Contacto')
        pessoa.localidade = request.POST.get('Localidade')
        pessoa.save()

        messages.success(request, 'Alterações gravadas com sucesso!')
        return redirect('siteY:meus_dados')

    return render(request, 'siteY/meus_dados.html', {'user': user, 'pessoa': pessoa})


def meus_gostos(request):
    user = request.user
    filmes_curtidos = Filme.objects.filter(liked=user)
    series_curtidas = Serie.objects.filter(liked=user)
    return render(request, 'siteY/meus_gostos.html', {'filmes_curtidos': filmes_curtidos, 'series_curtidas': series_curtidas})

@login_required(login_url='/siteY/login')
def adicionarfilme(request):
    if request.method == 'POST':
        titulo = request.POST.get('titulo')
        descricao = request.POST.get('descricao')
        ano = request.POST.get('ano')
        duracao = request.POST.get('duracao')
        genero = request.POST.get('genero')
        img = request.FILES['imagem']
        filme = Filme(titulo=titulo, descricao=descricao, ano_lancamento=ano, duracao_minutos=duracao, genero=genero, imagem=img)
        filme.user = request.user
        filme.save()

        return render(request, 'siteY/homepage.html')

    return render(request, 'siteY/addfilme.html')

@login_required(login_url='/siteY/login')
def adicionarserie(request):
    if request.method == 'POST':
        titulo = request.POST.get('titulo')
        descricao = request.POST.get('descricao')
        ano = request.POST.get('ano')
        temporadas = request.POST.get('temporadas')
        episodios = request.POST.get('episodios')
        genero = request.POST.get('genero')
        img = request.FILES['imagem']
        serie = Serie(titulo=titulo, descricao=descricao, ano_lancamento=ano, temporadas=temporadas, episodios=episodios, genero=genero, imagem=img)
        serie.user = request.user
        serie.save()

        return render(request, 'siteY/homepage.html')

    return render(request, 'siteY/addserie.html')

def terminarsessao(request):
    logout(request)
    return HttpResponseRedirect(reverse('siteY:login'))

def listar_filmes(request):
    filmes = Filme.objects.all().order_by('-data_adicao')
    return render(request, 'siteY/listar_filmes.html', {'filmes': filmes})

def listar_series(request):
    series = Serie.objects.all().order_by('-data_adicao')
    return render(request, 'siteY/listar_series.html', {'series': series})


def detalhes_filme(request, filme_id):
    filme = get_object_or_404(Filme, pk=filme_id)
    return render(request, 'siteY/detalhes_filme.html', {'filme': filme})

def detalhes_serie(request, serie_id):
    serie = get_object_or_404(Serie, pk=serie_id)
    return render(request, 'siteY/detalhes_serie.html', {'serie': serie})

@login_required
def likepost_serie(request, serie_id):
    try:
        serie_selecionada = Serie.objects.get(pk=serie_id)
    except Serie.DoesNotExist:
        return HttpResponseNotFound("Série não encontrada.")

    if request.method == 'POST':
        user = request.user
        if user in serie_selecionada.liked.all():
            serie_selecionada.liked.remove(user)
        else:
            serie_selecionada.liked.add(user)
        like_serie, created = Like_serie.objects.get_or_create(user=user, serie_id=serie_id)
        if not created:
            if like_serie.valor == 'Like':
                like_serie.valor = 'Unlike'
            else:
                like_serie.valor = 'Like'
            like_serie.save()
        return HttpResponseRedirect(reverse('siteY:detalhes_serie', args=[serie_id]))


@login_required
def likepost_filme(request, filme_id):
    try:
        filme_selecionado = Filme.objects.get(pk=filme_id)
    except Filme.DoesNotExist:
        return HttpResponseNotFound("Filme não encontrado.")

    if request.method == 'POST':
        user = request.user
        if user in filme_selecionado.liked.all():
            filme_selecionado.liked.remove(user)
        else:
            filme_selecionado.liked.add(user)
        like_filme, created = Like_filme.objects.get_or_create(user=user, filme_id=filme_id)
        if not created:
            if like_filme.valor == 'Like':
                like_filme.valor = 'Unlike'
            else:
                like_filme.valor = 'Like'
            like_filme.save()
        return HttpResponseRedirect(reverse('siteY:detalhes_filme', args=[filme_id]))


@login_required
def adicionar_comentario_filme(request, filme_id):
    filme = get_object_or_404(Filme, pk=filme_id)

    if request.method == 'POST':
        com = request.POST['comentario']

        if com.strip():  # Verifica se o campo de comentário contém algum texto
            comentario = Comentarios_filme(user=request.user, filme=filme, comentario=com)
            comentario.save()
        else:
            messages.error(request, 'Digite pelo menos uma letra antes de comentar.')

    return HttpResponseRedirect(reverse('siteY:detalhes_filme', args=[filme_id]))

@login_required
def adicionar_comentario_serie(request, serie_id):
    serie = get_object_or_404(Serie, pk=serie_id)

    if request.method == 'POST':
        com = request.POST['comentario']

        if com.strip():  # Verifica se o campo de comentário contém algum texto
            comentario = Comentarios_serie(user=request.user, serie=serie, comentario=com)
            comentario.save()
        else:
            messages.error(request, 'Digite pelo menos uma letra antes de comentar.')

    return HttpResponseRedirect(reverse('siteY:detalhes_serie', args=[serie_id]))

def pesquisar(request):
    query = request.GET.get('q')
    filmes = Filme.objects.filter(titulo__icontains=query)
    series = Serie.objects.filter(titulo__icontains=query)
    return render(request, 'siteY/pesquisar.html', {'filmes': filmes, 'series': series})

def recuperarPassword(request):
    if request.method == 'POST':
        Username = request.POST['Username']
        Email = request.POST['Email']

        user = User.objects.filter(username=Username, email=Email).first()
        if user:
            if User.objects.filter(username=Username).exists():

                html_message = render_to_string('siteY/mudarPassmail.html', {'username': Username})
                plain_message = strip_tags(html_message)

                send_mail(
                    'Mudança de Password',
                    plain_message,

SITE/SITE/siteY/templates/siteY/adicionar_comentario_filme.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Adicionar Comentário</title>
</head>
<body>
    <h2>Adicionar Comentário</h2>
    <form method="post" action="{% url 'adicionar_comentario_filme' filme.id=filme.id %}">
        {% csrf_token %}
        <div>
            <label for="id_comentario">Comentário:</label><br>
            <textarea id="id_comentario" name="comentario" rows="4" cols="50"></textarea>
        </div>
        <br>
        <button type="submit">Enviar</button>
    </form>
</body>
</html>

SITE/SITE/siteY/templates/siteY/admin.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Título</title>
    <link rel="stylesheet" type="text/css" href="{% static 'SiteY/admin.css' %}">
</head>
<body>
    <header class="header">
        <div class="logo">
            <a href="{% url 'siteY:homepage' %}">
                <img src="{% static 'SiteY/images/filme.jpg' %}">
            </a>
        </div>
        <div class="search-bar">
            <form action="{% url 'siteY:pesquisar' %}" method="GET">
                <input type="text" id="search" name="q" placeholder="Pesquisar...">
                <button type="submit">Buscar</button>
            </form>
        </div>
            <div class="pub-button">
                <button onclick="window.location.href='{% url 'siteY:addfilme' %}'">Adicionar Filme</button>
            </div>
            <div class="pub-button">
                <button onclick="window.location.href='{% url 'siteY:addserie' %}'">Adicionar Série</button>
            </div>
            <div class="pub-button">
                <button onclick="window.location.href='{% url 'siteY:listar_filmes' %}'">Filmes</button>
            </div>
            <div class="pub-button">
                <button onclick="window.location.href='{% url 'siteY:listar_series' %}'">Séries</button>
            </div>
        <div class="home">
            <a href="{% url 'siteY:homepage' %}">
                <img src="{% static 'SiteY/images/home.png' %}" alt="Home" width="35" height="35">
            </a>
        </div>
        <div class="perfil">
            <a href="{% url 'siteY:perfil' %}">
                <img src="{% static 'SiteY/images/perfil.jpg' %}" alt="Home" width="35" height="35">
            </a>
        </div>
        <div class="logout">
            <a href="{% url 'siteY:login' %}">
                <img src="{% static 'SiteY/images/logout.png' %}" alt="Logout" width="35" height="35">
            </a>
        </div>
    </header>
    <h1 class="users-title">Usuários</h1>
<div class="users-container">
    <div class="users-list">
        {% for user in users %}
        <div class="user">
    <p>{{ user.username }} - {{ user.email }}</p>
    <div class="user-buttons">
        <a href="{% url 'siteY:editar_user' user.id %}">
        <button class="edit-button">Editar</button>
        </a>
        <form action="{% url 'siteY:apagaruser' user.id %}" method="post" class="delete-form">
            {% csrf_token %}
            <button type="submit" class="delete-button">Apagar</button>
        </form>
    </div>
</div>
        {% endfor %}
    </div>
</div>

      <h1 class="movie-title">Filmes</h1>
    <div class="movie-container">
        {% for filme in filmes %}
        <div class="movie">
            <a href="{% url 'siteY:detalhes_filme' filme.id %}">
                <img src="{{ filme.imagem.url }}" alt="{{ filme.titulo }}">
                <h2>{{ filme.titulo }}</h2>
            </a>
            <div class="movie-buttons">
        <a href="{% url 'siteY:editar_filme' filme.id %}">
            <button class="edit-button">Editar</button>
        </a>
        <form action="{% url 'siteY:apagar_filme' filme.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="delete-button">Apagar</button>
        </form>
    </div>
        </div>
        {% endfor %}
    </div>

    <h1 class="series-title">Séries</h1>
    <div class="series-container">
        {% for serie in series %}
        <div class="serie">
            <a href="{% url 'siteY:detalhes_serie' serie.id %}">
                <img src="{{ serie.imagem.url }}" alt="{{ serie.titulo }}">
                <h2>{{ serie.titulo }}</h2>
            </a>
            <div class="serie-buttons">
        <a href="{% url 'siteY:editar_serie' serie.id %}">
            <button class="edit-button">Editar</button>
        </a>
        <form action="{% url 'siteY:apagar_serie' serie.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="delete-button">Apagar</button>
        </form>
    </div>
        </div>
        {% endfor %}
    </div>
</body>
</html>

SITE/SITE/siteY/templates/siteY/detalhes_filme.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Lista de Filmes</title>
    <link rel="stylesheet" type="text/css" href="{% static 'SiteY/detalhes_filme.css' %}">
</head>
<body>
   <header class="header">
    <div class="logo">
        <a href="{% url 'siteY:homepage' %}">
            <img src="{% static 'SiteY/images/filme.jpg' %}">
        </a>
     </div>
    <div class="search-bar">
        <input type="text" id="search" name="search" placeholder="Pesquisar...">
        <button type="submit">Buscar</button>
    </div>
    <div class="pub-button">
                <button onclick="window.location.href='{% url 'siteY:addfilme' %}'">Adicionar Filme</button>
            </div>
            <div class="pub-button">
                <button onclick="window.location.href='{% url 'siteY:addserie' %}'">Adicionar Série</button>
            </div>
            <div class="pub-button">
                <button onclick="window.location.href='{% url 'siteY:listar_filmes' %}'">Filmes</button>
            </div>
            <div class="pub-button">
                <button onclick="window.location.href='{% url 'siteY:listar_series' %}'">Séries</button>
            </div>
    </div>
       <div class="home">
        <a href="{% url 'siteY:homepage' %}">
            <img src="{% static 'SiteY/images/home.png' %}" alt="Home" width="35" height="35">
        </a>
    </div>
    <div class="perfil">
        <a href="{% url 'siteY:perfil' %}">
            <img src="{% static 'SiteY/images/perfil.jpg' %}" alt="Home" width="35" height="35">
        </a>
    </div>
    <div class="logout">
        <a href="{% url 'siteY:login' %}">
            <img src="{% static 'SiteY/images/logout.png' %}" alt="Logout" width="35" height="35">
        </a>
    </div>
</header>

<div class="filme-details">
    <h1>{{ filme.titulo }}</h1>
    <img src="{{ filme.imagem.url }}" alt="{{ filme.titulo }}">
    <p>{{ filme.descricao }}</p>
    <p>Ano de Lançamento: {{ filme.ano_lancamento }}</p>
    <p>Duração: {{ filme.duracao_minutos }} minutos</p>
    <p>Gênero: {{ filme.genero }}</p>
     <div class="like-data-wrapper">
            <form method="POST" action="{% url 'siteY:likepost_filme' filme.id %}">
            {% csrf_token %}
            {% if user in filme.liked.all %}
                <button type="submit" name="action" value="dislike" class="like-button">Dislike</button>
            {% else %}
                <button type="submit" name="action" value="like" class="like-button">Like</button>
            {% endif %}
            </form>
            </div>
            {% if filme.total_likes_filme == 1 %}
                <p>1 like</p>
            {% else %}
                <p>{{ filme.total_likes_filme }} likes</p>
            {% endif %}
    <!-- Seção de Comentários -->
            <div class="comentarios">
            <strong>---------------------------------- Comentários ----------------------------------</strong>
            {% if filme.comentarios_filme_set.count < 1 %}
            <p>Ainda não existem comentários, seja o primeiro!</p>
            {% else %}
            {% for com in filme.comentarios_filme_set.all %}
            <div class="comentario-wrapper">
                <strong>{{ com.user }} -</strong>
                {{ com.comentario }}
            </div>
        {% endfor %}
        {% endif %}
            </div>

            <!-- Formulário para adicionar comentário -->
            <form method="POST" action="{% url 'siteY:adicionar_comentario_filme' filme.id %}">
                {% csrf_token %}
                <textarea class="comment-bar" name="comentario" rows="3" placeholder="Adicione um comentário"></textarea>
                <button type="submit">Comentar</button>
            </form>
        </div>
</div>

</body>
</html>

SITE/SITE/siteY/templates/siteY/editar_serie.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Título</title>
    <link rel="stylesheet" type="text/css" href="{% static 'SiteY/editar_serie.css' %}">
</head>
<body>
<header class="header">
    <div class="logo">
        <a href="{% url 'siteY:homepage' %}">
            <img src="{% static 'SiteY/images/filme.jpg' %}">
        </a>
    </div>
    <div class="search-bar">
        <form action="{% url 'siteY:pesquisar' %}" method="GET">
            <input type="text" id="search" name="q" placeholder="Pesquisar...">
            <button type="submit">Buscar</button>
        </form>
    </div>
    <div class="pub-button">
        <button onclick="window.location.href='{% url 'siteY:addfilme' %}'">Adicionar Filme</button>
    </div>
    <div class="pub-button">
        <button onclick="window.location.href='{% url 'siteY:addserie' %}'">Adicionar Série</button>
    </div>
    <div class="pub-button">
        <button onclick="window.location.href='{% url 'siteY:listar_filmes' %}'">Filmes</button>
    </div>
    <div class="pub-button">
        <button onclick="window.location.href='{% url 'siteY:listar_series' %}'">Séries</button>
    </div>
    <div class="home">
        <a href="{% url 'siteY:homepage' %}">
            <img src="{% static 'SiteY/images/home.png' %}" alt="Home" width="35" height="35">
        </a>
    </div>
    <div class="perfil">
        <a href="{% url 'siteY:perfil' %}">
            <img src="{% static 'SiteY/images/perfil.jpg' %}" alt="Home" width="35" height="35">
        </a>
    </div>
    <div class="logout">
        <a href="{% url 'siteY:login' %}">
            <img src="{% static 'SiteY/images/logout.png' %}" alt="Logout" width="35" height="35">
        </a>
    </div>
</header>

<div class="main-content">
    <div class="container-wrapper">
        <div class="content">
            <h2>Editar Serie</h2>
<div class="container">
    <form action="{% url 'siteY:editar_serie' serie.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            <label for="titulo">Título:</label>
            <input type="text" id="titulo" name="titulo" value="{{ serie.titulo }}" required><br>
        </div>
        <div>
            <label for="descricao">Descrição:</label>
            <textarea id="descricao" name="descricao" rows="4">{{ serie.descricao }}</textarea><br>
        </div>
        <div>
            <label for="ano">Ano de Lançamento:</label>
            <input type="number" id="ano" name="ano" min="1900" max="2099" step="1" value="{{ serie.ano_lancamento }}"><br>
        </div>
        <div>
            <label for="temporadas">Temporadas:</label>
            <input type="number" id="temporadas" name="temporadas" min="1" step="1" value="{{ serie.temporadas }}"><br>
        </div>
        <div>
            <label for="episodios">Episódios:</label>
            <input type="number" id="episodios" name="episodios" min="1" step="1" value="{{ serie.episodios }}"><br>
        </div>
        <div>
            <label for="genero">Gênero:</label>
            <input type="text" id="genero" name="genero" value="{{ serie.genero }}"><br>
        </div>
        <div>
            <img src="{{ serie.imagem.url }}" alt="Imagem da série" width="200" height="200">
            <label for="imagem">Imagem:</label>
            <input type="file" id="imagem" name="imagem"><br>
        </div>
        <button type="submit">Gravar</button>
    </form>
</div>
        </div>
    </div>
</div>

</body>
</html>

SITE/SITE/siteY/templates/siteY/oi.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'siteY/login.css' %}">
</head>
<body>

{% if error_message %}
    <p>{{ error_message }}</p>
{% endif %}

<div class="login-form-container">
    <form method="post" action="{% url 'siteY:login' %}">
        {% csrf_token %}
        <input type="text" placeholder="Nome de utilizador" name="email" required>
        <br><br>
        <input type="password" placeholder="Palavra-passe" name="password" required>
        <br><br>
        <input type="submit" class="login" value="Login">
    </form>
</div>

<div class="register-container">
    <p>Não tens uma conta?</p>
    <div class="button-container">
        <a href="{% url 'siteY:criarconta' %}">Regista-te</a>
    </div>
</div>
<div class="forgot-password">
    <a href="{% url 'siteY:recuperarPassword' %}">Esqueceu sua senha?</a>
</div>
</body>
</html>